name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: [ "main" ] # Executa sempre que você enviar código para o branch main

# Define as permissões necessárias para o token do GitHub Actions publicar no Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que builds simultâneos não batam cabeça
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout o código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci --legacy-peer-deps

      - name: Compilar o projeto (Build do Vite)
        run: npm run build

      - name: Configurar as Páginas do GitHub
        uses: actions/configure-pages@v4

      - name: Upload dos arquivos compilados (Pasta dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Garante que vai enviar a pasta gerada pelo Vite

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
